document.writeln("<!DOCTYPE html PUBLIC \'-//W3C//DTD XHTML 1.0 Strict//EN\' \'http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\'>");
document.writeln("<html xmlns=\'http://www.w3.org/1999/xhtml\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'utf-8\' />");
document.writeln("    <title>footer</title>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/reset.css\'/>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/footer.css\'/>");
document.writeln("    <script type=\'text/javascript\' src=\'scripts/jquery-3.2.1.js\'></script>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<!-- Footer -->");
document.writeln("<div class=\'pc-g-footer\'>");
document.writeln("    <div class=\'l-wrapper\'>");
document.writeln("        <div class=\'pc-g-footer-contact\'>");
document.writeln("            <h2 class=\'pc-g-footer-title\'>联系我们</h2>");
document.writeln("            <ul class=\'pc-mod-content-list\'>");
document.writeln("                <li class=\'pc-mod-content-item\'>");
document.writeln("                    <a href=\'//developer.rongcloud.cn/ticket\' target=\'_blank\'>技术支持</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'pc-mod-content-item\'>");
document.writeln("                    <span class=\'pc-mod-content-item-first\'>业务咨询</span>");
document.writeln("                    <span>400 - 919 - 9066</span>");
document.writeln("                </li>");
document.writeln("                <li class=\'pc-mod-content-item\'>");
document.writeln("                    <span class=\'pc-mod-content-item-first\'>市场合作</span>");
document.writeln("                    <span>010 - 57973273</span>");
document.writeln("                </li>");
document.writeln("                <li class=\'pc-mod-content-item\'>");
document.writeln("                    <span class=\'pc-mod-content-item-first\'>联系销售</span>");
document.writeln("                    <span>13161856839</span>");
document.writeln("                </li>");
document.writeln("                <li class=\'pc-mod-content-item\'>");
document.writeln("                    <span class=\'pc-mod-content-item-first\'>联系 ISV/SI 伙伴经理 </span>");
document.writeln("                    <span>18612309791</span>");
document.writeln("                </li>");
document.writeln("                <li class=\'pc-mod-content-item\'>");
document.writeln("                    <span class=\'pc-mod-content-item-first\'>技术支持邮箱</span>");
document.writeln("                    <a href=\'mailto:support@rongcloud.cn\'>support@rongcloud.cn</a>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        <div class=\'pc-g-footer-developer\'>");
document.writeln("            <h2 class=\'pc-g-footer-title\'>开发者服务</h2>");
document.writeln("            <ul class=\'pc-mod-content-list\'>");
document.writeln("                <li class=\'pc-mod-content-item\'>");
document.writeln("                    <a href=\'//developer.rongcloud.cn/account/pay\' target=\'_blank\'>付费充值</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'pc-mod-content-item\'>");
document.writeln("                    <a href=\'/downloads\'>SDK 下载</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'pc-mod-content-item\'>");
document.writeln("                    <a href=\'/changelog\'>SDK 版本更新记录</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'pc-mod-content-item\'>");
document.writeln("                    <a href=\'/changelog/sealtalk\'>SealTalk 版本更新记录</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'pc-mod-content-item\'>");
document.writeln("                    <a href=\'//blog.rongcloud.cn/?cat=3\' target=\'_blank\'>活动沙龙</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'pc-mod-content-item\'>");
document.writeln("                    <a href=\'//blog.rongcloud.cn/?cat=4\' target=\'_blank\'>开发教程</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'pc-mod-content-item\'>");
document.writeln("                    <a href=\'/partners\'>第三方开发支持</a>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        <div class=\'pc-g-footer-about\'>");
document.writeln("            <h2 class=\'pc-g-footer-title\'>关于我们</h2>");
document.writeln("            <ul class=\'pc-mod-content-list\'>");
document.writeln("                <li class=\'pc-mod-content-item\'>");
document.writeln("                    <a href=\'/about\'>公司简介</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'pc-mod-content-item\'>");
document.writeln("                    <a href=\'/about#contact\'>联系方式</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'pc-mod-content-item\'>");
document.writeln("                    <a href=\'/jobs\'>加入我们</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'pc-mod-content-item\'>");
document.writeln("                    <a href=\'/cooper\'>市场 &amp; 服务伙伴</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'pc-mod-content-item\'>");
document.writeln("                    <a href=\'/link\'>友情链接</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'pc-mod-content-item\'>");
document.writeln("                    <a href=\'/tos\'>服务条款</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'pc-mod-content-item\'>");
document.writeln("                    <a href=\'/reports\'>媒体报道</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'pc-mod-content-item\'>");
document.writeln("                    <a href=\'//blog.rongcloud.cn/\' target=\'_blank\'>融云 Blog</a>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("");
document.writeln("        </div>");
document.writeln("        <div class=\'pc-mod-footer-media\'>");
document.writeln("            <img class=\'pc-mod-qr-code\' width=\'162\' src=\'/pc/images/code_log_wexin.jpg\'>");
document.writeln("            <div class=\'pc-mod-footer-weixin\'>融云公众号</div>");
document.writeln("            <div class=\'pc-mod-footer-weibo\'>");
document.writeln("                <a href=\'http://weibo.com/rongcloud\' target=\'_blank\'>官方微博</a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'pc-g-footer-copyright\'>");
document.writeln("        <p class=\'l-column-left\'>Copyright 2017 RongCloud</p>");
document.writeln("        <a class=\'l-column-left pc-g-record-number\' target=\'_blank\' href=\'http://www.beian.gov.cn/portal/registerSystemInfo?&amp;recordcode=11010502033445\'>京公网安备 11010502033445 号</a>");
document.writeln("        <a class=\'l-column-left\' target=\'_blank\' href=\'http://www.miitbeian.gov.cn/\'>京 ICP 备 15042119 号 - 1</a>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("</html>");